# Generated by Django 2.2.5 on 2019-10-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuraciones',
            fields=[
                ('id_Configuracion', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id_Fotos', models.AutoField(primary_key=True, serialize=False)),
                ('Valor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id_Idioma', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PuntosInteres',
            fields=[
                ('id_PuntosInteres', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
                ('Descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id_Ruta', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=40)),
                ('altitud', models.CharField(max_length=20)),
                ('longitud', models.CharField(max_length=20)),
                ('Archivoruta', models.CharField(max_length=20)),
                ('Descripcion', models.CharField(max_length=20)),
                ('Duracion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id_Tema', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
