# Generated by Django 2.2.5 on 2019-10-17 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0002_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciones',
            name='idIdiomas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Modulos.Idiomas'),
        ),
        migrations.AddField(
            model_name='configuraciones',
            name='idTemas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Modulos.Temas'),
        ),
        migrations.CreateModel(
            name='Rutas_Fotos',
            fields=[
                ('id_Ruta', models.AutoField(primary_key=True, serialize=False)),
                ('idFotos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulos.Fotos')),
                ('idpuntosinteres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulos.PuntosInteres')),
            ],
        ),
        migrations.CreateModel(
            name='Puntosinteres_fotos',
            fields=[
                ('id_PuntosInteres_fotos', models.AutoField(primary_key=True, serialize=False)),
                ('idFotos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulos.Fotos')),
                ('idRutas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulos.Rutas')),
            ],
        ),
    ]
